<?php
namespace Codeception\Module;

// here you can define custom actions
// all public methods declared in helper class will be available in $I


class ApiHelper extends \Codeception\Module
{
    /**
     * @var \Codeception\Module\REST
     */
    private $rest;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->rest = $this->getModule('REST');
    }

    public function login($username, $password, $valid = true)
    {
        $this->rest->sendPOST('?r=user/login', ['username' => $username, 'password' => $password]);
        $this->rest->seeResponseCodeIs($valid?200:409);
        $this->rest->seeResponseIsJson();
    }
}
